PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZHCM_ESS_APPROV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZHCM_ESS_APPROV-APP_ID .
    FIELD ZHCM_ESS_APPROV-APPROVER_SEQ .
    FIELD ZHCM_ESS_APPROV-APPROVER_TYPE .
    FIELD ZHCM_ESS_APPROV-PLANS .
    FIELD ZHCM_ESS_APPROV-PERNR .
    FIELD ZHCM_ESS_APPROV-APPROVER_RULE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZHCM_ESS_APPROV-APP_ID .
    FIELD ZHCM_ESS_APPROV-APPROVER_SEQ .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
