*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZHCM_RULE_L_MV..................................*
FORM GET_DATA_ZHCM_RULE_L_MV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZHCM_APPROV_R_L WHERE
(VIM_WHERETAB) .
    CLEAR ZHCM_RULE_L_MV .
ZHCM_RULE_L_MV-APPROVER_RULE =
ZHCM_APPROV_R_L-APPROVER_RULE .
ZHCM_RULE_L_MV-PERNR =
ZHCM_APPROV_R_L-PERNR .
<VIM_TOTAL_STRUC> = ZHCM_RULE_L_MV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZHCM_RULE_L_MV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZHCM_RULE_L_MV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZHCM_RULE_L_MV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZHCM_APPROV_R_L WHERE
  APPROVER_RULE = ZHCM_RULE_L_MV-APPROVER_RULE AND
  PERNR = ZHCM_RULE_L_MV-PERNR .
    IF SY-SUBRC = 0.
    DELETE ZHCM_APPROV_R_L .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZHCM_APPROV_R_L WHERE
  APPROVER_RULE = ZHCM_RULE_L_MV-APPROVER_RULE AND
  PERNR = ZHCM_RULE_L_MV-PERNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZHCM_APPROV_R_L.
    ENDIF.
ZHCM_APPROV_R_L-APPROVER_RULE =
ZHCM_RULE_L_MV-APPROVER_RULE .
ZHCM_APPROV_R_L-PERNR =
ZHCM_RULE_L_MV-PERNR .
    IF SY-SUBRC = 0.
    UPDATE ZHCM_APPROV_R_L ##WARN_OK.
    ELSE.
    INSERT ZHCM_APPROV_R_L .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZHCM_RULE_L_MV-UPD_FLAG,
STATUS_ZHCM_RULE_L_MV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZHCM_RULE_L_MV.
  SELECT SINGLE * FROM ZHCM_APPROV_R_L WHERE
APPROVER_RULE = ZHCM_RULE_L_MV-APPROVER_RULE AND
PERNR = ZHCM_RULE_L_MV-PERNR .
ZHCM_RULE_L_MV-APPROVER_RULE =
ZHCM_APPROV_R_L-APPROVER_RULE .
ZHCM_RULE_L_MV-PERNR =
ZHCM_APPROV_R_L-PERNR .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZHCM_RULE_L_MV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZHCM_RULE_L_MV-APPROVER_RULE TO
ZHCM_APPROV_R_L-APPROVER_RULE .
MOVE ZHCM_RULE_L_MV-PERNR TO
ZHCM_APPROV_R_L-PERNR .
MOVE SY-MANDT TO
ZHCM_APPROV_R_L-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZHCM_APPROV_R_L'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZHCM_APPROV_R_L TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZHCM_APPROV_R_L'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
